# This workflow will run all checks required for a PR to be merged.

name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.37.0

      - name: Initialize project
        run: deno task dev

      - name: fmt
        run: deno fmt

      - name: test
        run: deno task test
